name: "Build & Release"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    permissions:
      contents: read
      deployments: write
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # Or your desired Java version
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - name: Check Java Version
        run: flutter doctor --verbose
      - name: Update Gradle Version
        run: |
          JAVA_VERSION=$(flutter doctor --verbose | grep "Java version" | awk '{print $3}')
          if [[ "$JAVA_VERSION" == "11" ]]; then
            sed -i '' 's/distributionUrl=.*/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-7.4-all.zip/' android/gradle/wrapper/gradle-wrapper.properties
          elif [[ "$JAVA_VERSION" == "17" ]]; then
            sed -i '' 's/distributionUrl=.*/distributionUrl=https\:\/\/services.gradle.org\/distributions\/gradle-8.0-all.zip/' android/gradle/wrapper/gradle-wrapper.properties
          fi
      - name: Clean and Rebuild
        run: flutter clean && flutter build apk --release --split-per-abi






# push to master, main, develop
# pull request on main master